version: '3.4'

services:
  one-api:
    image: shown1985/one-api:latest
    container_name: one-api
    restart: always
    command: --log-dir /app/logs
    ports:
      - "3000:3000"
    volumes:
      - /opt/one-api/data/oneapi:/data
      - /opt/one-api/logs:/app/logs
    environment:
      - SQL_DSN=oneapi:oneApi^@tcp(rm-f8z7123artd26c2c3.mysql.rds.aliyuncs.com:3306)/one-api  # 修改此行，或注释掉以使用 SQLite 作为数据库
      - REDIS_CONN_STRING=redis://:shawnRedis^@192.168.100.252:21379/3
      - SESSION_SECRET=2AaDoQJKcG  # 修改为随机字符串
      - TZ=Asia/Shanghai
#      - NODE_TYPE=slave  # 多机部署时从节点取消注释该行
#      - SYNC_FREQUENCY=60  # 需要定期从数据库加载数据时取消注释该行
#      - FRONTEND_BASE_URL=https://openai.justsong.cn  # 多机部署时从节点取消注释该行
    healthcheck:
      test: [ "CMD-SHELL", "wget -q -O - http://localhost:3000/api/status | grep -o '\"success\":\\s*true' | awk -F: '{print $2}'" ]
      interval: 30s
      timeout: 10s
      retries: 3